### ISSUE TITLE
DHCP support

### ISSUE THREAD

**Issue by lalithsuresh** [lalithsuresh/odin-master#2]
Have the master tap into DHCP messages at switches to keep track of a client's IP address.

**Comment by rmerz** [comment]
You can simply read/parse the lease database/file

**Comment by lalithsuresh** [comment]
I already have some code to pick up DHCP response packets and see the
IP addresses that clients are being assigned. Just need to fit this
into the Odin/LVAP protocol. I'll wrap this up by tomorrow.

On Wed, Jul 11, 2012 at 10:24 PM, Ruben Merz
reply@reply.github.com
wrote:

> You can simply read/parse the lease database/file
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lalithsuresh/odin/issues/2#issuecomment-6918232

## 

Lalith Suresh
www.lalith.in

**Comment by lalithsuresh** [comment]
Commit: 71da968f59e26471cc354cf0d0bd252e3887d0e8
